# services:
#   keycloak_server:
#     image: quay.io/keycloak/keycloak:24.0.4
#     environment:
#       - KEYCLOAK_ADMIN=admin
#       - KEYCLOAK_ADMIN_PASSWORD=admin
#     ports:
#       - 8080:8080
#     command: start-dev
#     volumes:
#       - dicicip_keycloak:/opt/keycloak

# volumes:
#   dicicip_keycloak:
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
    depends_on:
      - postgresql
    volumes:
      - './mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme'
volumes:
  postgresql_data:
    driver: local